const productActionTypes = {
    UPDATE_PRODUCT_LIST: 'UPDATE_PRODUCT_LIST',
    SELECT_PRODUCT:'SELECT_PRODUCT',
    UPDATE_SELECTED_PRODUCT_VALUES: 'UPDATE_SELECTED_PRODUCT_VALUES'
}

export default productActionTypes;